# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_auto_20161205_1304'),
        ('presentation', '0004_auto_20161205_2042'),
    ]

    operations = [
    ]
